seed = 1001
width = 512
height = 512
world_type = "Supercontinent"

[climate]
global_temperature_offset = 0.1
global_humidity_offset = 0.1
polar_amplification = 1.0
climate_latitude_exponent = 0.8

[islands]
island_density = 0.2             # мало островов
min_island_size = 200

num_regions = 15

[terrain]
elevation_power = 0.6            # очень плоский центр
smooth_radius = 2                # сильное сглаживание
mountain_compression = 0.85      # почти нет гор
total_provinces = 120