seed = 42
width = 512
height = 512
world_type = "IceAgeEarth"

[climate]
global_temperature_offset = -0.7
polar_amplification = 1.8

[islands]
island_density = 0.3
min_island_size = 150

num_regions = 120